<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function starter_custom_theme() {
  $info = [];

  $info['style_guide'] = [
    'variables' => [
      'content' => NULL,
    ],
  ];

  $info['server_theme_person_card'] = [
    'variables' => [
      'image' => NULL,
      'name' => NULL,
      'position' => NULL,
      'role' => NULL,
      'email' => NULL,
      'phone' => NULL,
    ],
  ];

  $info['server_theme_person_cards'] = [
    'variables' => [
      'cards' => NULL,
    ],
  ];

  return $info;
}
